# Site settings
title: Zaks Open Source Blog
email: zak.hassan1010@gmail.com
description: "Learn About Open Source Middleware, Cloud, Openshift and Messaging"
baseurl: ""
url: "http://zmhassan.github.io"

# Build settings
markdown: kramdown
permalink: pretty

layout: post
title: Blogging Like a Hacker
 